(defun myfunc ( x y / my_x my_y)
  (setq my_y y)
  (while (<= my_y (+ 120 y))
	 (setq my_x 0)
	 (while (<= my_x (+ 120 x))
		(command "_.line" (list (- my_x 2) my_y) (list (+ my_x 2) my_y) '())
		(command "_.line" (list my_x (- my_y 2)) (list my_x (+ my_y 2)) '())
		(setq my_x (+ my_x 10))
		)
	 (setq my_y (+ my_y 40))
	 )
	(princ)
  )
